### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by debuggingfuture** [code4hk/code4hk.github.io#6]
I added resource id UA-48536294-3 for blog.code4.hk

Let's use the new version of [analytics.js](https://developers.google.com/analytics/devguides/collection/analyticsjs/)
seems must include in the head

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48536294-3', 'code4.hk');
  ga('send', 'pageview');

</script>
```

where to add? this?
https://github.com/code4hk/blog/blob/gh-pages/_includes/JB/setup

**Comment by debuggingfuture** [comment]
@hupili @gilbertwat

**Comment by hupili** [comment]
I created a GA before and shared the account with you. To change the ID or analytics script, you can check out `_config.yml` and `_includes/JB/analytics-providers/google`.

```
$grep 'tracking_id' * -R 
_config.yml:    tracking_id : 'UA-48349521-2'
_includes/JB/analytics-providers/google:  _gaq.push(['_setAccount', '{{ site.JB.analytics.google.tracking_id }}']);
```

**Comment by debuggingfuture** [comment]
sorry did not aware, which account is it?
UA-48536294-3 is under code4hk@gmail.com now

updated above in https://github.com/code4hk/blog/commit/fbbfd4932a17dd5837a426509b27f486bfeabee6

may need to wait for refresh
![image](https://f.cloud.github.com/assets/1883877/2400734/f723cd98-aa0d-11e3-8b28-e0b405031a49.png)

**Comment by hupili** [comment]
I fixed the yaml error in b916d2216bf8e262e5b6dc16c8ace4c228598830 and changed to new version of GA in 9e054b1c4ccb7ce93f269638c34ac967cf7e3ef9 

Try to check whether data come in later.

**Comment by debuggingfuture** [comment]
The code is now there, but didnt pick up by Google yet

**Comment by hupili** [comment]
The stat data may come by day. I just checked real-time visits and it works.
